jobs:
  build:
    env:
      CHROME_MIN_VERSION: ${{ matrix.chrome-min-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Show history
      run: git log --oneline -n 5
    - continue-on-error: true
      name: Install deps
      run: 'google-chrome --version

        sudo -E ./install-build-deps.sh

        '
    - continue-on-error: true
      name: Check environment
      run: 'which java

        java -Xmx32m -version

        javac -J-Xmx32m -version

        google-chrome --version

        '
    - continue-on-error: true
      name: Run pre-commit tests
      run: hooks/pre-commit
    - continue-on-error: true
      name: Run tests
      run: ant test -Dtest.shuffle=1 -Dtest.repeat=10
    - continue-on-error: true
      name: Package
      run: ant package
    strategy:
      matrix:
        include:
        - chrome-min-version: 49
        - chrome-min-version: 999
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
